service: website-meetup-contentful

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: handlers/app.handler
    stage: ${opt:stage, 'dev'}
    timeout: 300s
    events:
      - schedule: rate(1 day)
